// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA49yItU29-Ang2Kp4WG6l9giekh61q3_U',
    appId: '1:589805270139:web:ba5e0c35af0d8c17af1ede',
    messagingSenderId: '589805270139',
    projectId: 'virtual-bell',
    authDomain: 'virtual-bell.firebaseapp.com',
    databaseURL: 'https://virtual-bell-default-rtdb.firebaseio.com',
    storageBucket: 'virtual-bell.appspot.com',
    measurementId: 'G-N5KK5S5HHS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4saq4v6iU6rGqtw6bj2qzu0EthVQ1E00',
    appId: '1:589805270139:android:a5525e7adcbfe18caf1ede',
    messagingSenderId: '589805270139',
    projectId: 'virtual-bell',
    databaseURL: 'https://virtual-bell-default-rtdb.firebaseio.com',
    storageBucket: 'virtual-bell.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN82DjEez7cNcTxiq5BGZbl8ayAtuKSPs',
    appId: '1:589805270139:ios:d0c51066bb06cadbaf1ede',
    messagingSenderId: '589805270139',
    projectId: 'virtual-bell',
    databaseURL: 'https://virtual-bell-default-rtdb.firebaseio.com',
    storageBucket: 'virtual-bell.appspot.com',
    iosBundleId: 'com.example.virtualUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN82DjEez7cNcTxiq5BGZbl8ayAtuKSPs',
    appId: '1:589805270139:ios:d0c51066bb06cadbaf1ede',
    messagingSenderId: '589805270139',
    projectId: 'virtual-bell',
    databaseURL: 'https://virtual-bell-default-rtdb.firebaseio.com',
    storageBucket: 'virtual-bell.appspot.com',
    iosBundleId: 'com.example.virtualUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA49yItU29-Ang2Kp4WG6l9giekh61q3_U',
    appId: '1:589805270139:web:32ecb9509f7fed22af1ede',
    messagingSenderId: '589805270139',
    projectId: 'virtual-bell',
    authDomain: 'virtual-bell.firebaseapp.com',
    databaseURL: 'https://virtual-bell-default-rtdb.firebaseio.com',
    storageBucket: 'virtual-bell.appspot.com',
    measurementId: 'G-BCCHTP974R',
  );
}
